/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_hotel_proyecto_bd;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author emele
 */
public class MenuPrincipal_Gestion_Hotel_BD extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal_Gestion_Biblioteca
     */
    public MenuPrincipal_Gestion_Hotel_BD() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo_hotel.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNformulario_HOTEL = new javax.swing.JButton();
        BTNformulario_PAGO = new javax.swing.JButton();
        BTNformulario_TIPO_CATEGORIA = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BTNformulario_HABITACION = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        BTNformulario_CLIENTE = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        BTNformulario_RESERVACION = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        BTNformulario_FACTURA = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        BTNformulario_HOTEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotel.png"))); // NOI18N
        BTNformulario_HOTEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_HOTELActionPerformed(evt);
            }
        });

        BTNformulario_PAGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo_pago.jpg"))); // NOI18N
        BTNformulario_PAGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_PAGOActionPerformed(evt);
            }
        });

        BTNformulario_TIPO_CATEGORIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo_categoria.png"))); // NOI18N
        BTNformulario_TIPO_CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_TIPO_CATEGORIAActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 153, 0));
        jLabel13.setText("Formulario - Pago");

        jLabel14.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 0));
        jLabel14.setText("Administracion de Base de Datos");

        jLabel16.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 153, 0));
        jLabel16.setText("Formulario - Hotel");

        jLabel17.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 153, 0));
        jLabel17.setText("Formulario - Tipo Categoria");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facci.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uleam.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 153, 0));
        jLabel18.setText("Sistema Administrativo de un Hotel");

        BTNformulario_HABITACION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habitacion.png"))); // NOI18N
        BTNformulario_HABITACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_HABITACIONActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 153, 0));
        jLabel20.setText("Formulario - Habitacion");

        BTNformulario_CLIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        BTNformulario_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_CLIENTEActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 153, 0));
        jLabel21.setText("Formulario - Cliente");

        BTNformulario_RESERVACION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservacion.jpg"))); // NOI18N
        BTNformulario_RESERVACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_RESERVACIONActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 153, 0));
        jLabel22.setText("Formulario - Reservacion");

        BTNformulario_FACTURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.jpg"))); // NOI18N
        BTNformulario_FACTURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNformulario_FACTURAActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 153, 0));
        jLabel23.setText("Formulario -  Factura");

        jLabel24.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 153, 0));
        jLabel24.setText("5 - Nivel \"A\"");

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 204));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir del aplicativo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTNformulario_TIPO_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(BTNformulario_HOTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BTNformulario_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(BTNformulario_HABITACION, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(BTNformulario_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNformulario_RESERVACION, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel21)))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNformulario_FACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNformulario_CLIENTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNformulario_RESERVACION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNformulario_TIPO_CATEGORIA)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel16)
                                .addGap(4, 4, 4)
                                .addComponent(BTNformulario_HOTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(BTNformulario_HABITACION)))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNformulario_PAGO)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(BTNformulario_FACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNformulario_HOTELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_HOTELActionPerformed
        // TODO add your handling code here:
        Formulario_HOTEL_BD Tabla_HOTEL = new Formulario_HOTEL_BD();
        Tabla_HOTEL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNformulario_HOTELActionPerformed

    private void BTNformulario_PAGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_PAGOActionPerformed
        // TODO add your handling code here:
        Formulario_TIPO_PAGO_BD Tabla_PAGO = new Formulario_TIPO_PAGO_BD();
        Tabla_PAGO.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNformulario_PAGOActionPerformed

    private void BTNformulario_TIPO_CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_TIPO_CATEGORIAActionPerformed
        // TODO add your handling code here:
        Formulario_TIPO_CATEGORIA_BD Tabla_TIPO = new Formulario_TIPO_CATEGORIA_BD();
        Tabla_TIPO.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BTNformulario_TIPO_CATEGORIAActionPerformed

    private void BTNformulario_HABITACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_HABITACIONActionPerformed
        // TODO add your handling code here:
        Formulario_HABITACION_BD Tabla_HABITACION = new Formulario_HABITACION_BD();
        Tabla_HABITACION.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNformulario_HABITACIONActionPerformed

    private void BTNformulario_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_CLIENTEActionPerformed
        // TODO add your handling code here:
        Formulario_CLIENTE_BD Tabla_CLIENTE = new Formulario_CLIENTE_BD();
        Tabla_CLIENTE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNformulario_CLIENTEActionPerformed

    private void BTNformulario_RESERVACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_RESERVACIONActionPerformed
        // TODO add your handling code here:Ç
        Formulario_RESERVACION_BD Tabla_RESERVACION = new Formulario_RESERVACION_BD();
        Tabla_RESERVACION.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNformulario_RESERVACIONActionPerformed

    private void BTNformulario_FACTURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNformulario_FACTURAActionPerformed
        // TODO add your handling code here:
        Formulario_FACTURA_BD Tabla_FACTURA = new Formulario_FACTURA_BD();
        Tabla_FACTURA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNformulario_FACTURAActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Gestion_Hotel_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Gestion_Hotel_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Gestion_Hotel_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Gestion_Hotel_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal_Gestion_Hotel_BD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNformulario_CLIENTE;
    private javax.swing.JButton BTNformulario_FACTURA;
    private javax.swing.JButton BTNformulario_HABITACION;
    private javax.swing.JButton BTNformulario_HOTEL;
    private javax.swing.JButton BTNformulario_PAGO;
    private javax.swing.JButton BTNformulario_RESERVACION;
    private javax.swing.JButton BTNformulario_TIPO_CATEGORIA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
